### ISSUE TITLE
Signature help window appears behind completion window

### ISSUE THREAD

**Issue by yassiezar** [hrsh7th/cmp-nvim-lsp-signature-help#39]
I have a problem where the signature help hover window is placed behind the autocomplete suggestion window (see screenshot). I have my cmp configured to always run the completion engine, but trigger the signature help on ctrl+h. What you see below is what it looks like just after triggering the help. 

Is there a window configuration option I need to modify? I had a look at the options in cmp and lsp-zero, but nothing stood out

![image](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/assets/5284743/69405925-c641-40ea-be65-1372e7bb773e)

**Comment by nbl0** [comment]
Hello,

I'm experiencing the same issue as you. Have you found a solution?

Regards,

**Comment by yassiezar** [comment]
No unfortunately not. I've updated my Neovim and all my plugins, but the problem is still there.

**Comment by ahogen** [comment]
Fixed in my config by telling the `cmp` plugin to use `nvim_lsp_signature_help` as a "source", just like this project's README describes.

**Comment by yassiezar** [comment]
My cmp config includes `nvim_lsp_signature_help` as a source, but the window occlusion still happens for me.

![image](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/assets/5284743/eb0e984a-035a-43c0-aac2-bf88115fbcf0)
![image](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/assets/5284743/62dd7ada-aa2a-495b-9a6b-4dfba386fe0e)

**Comment by ahogen** [comment]
Ah you might be right. I'm in a C file right now and when I said it was working for me, I was referring to how it looks when I'm typing out arguments to a function, like this.

![image](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/assets/6827790/f14dab29-af46-439c-91d8-1664fc7efd59)

But yeah it looks like if the LSP completion pops up first and I try to `<Ctrl+n>` to cycle through the list of options in that list, then this signature thing can pop up on top of the LSP completion...?

![image](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/assets/6827790/a29bf7ed-9043-4cbe-b844-5eab2c62f496)
